import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';

import Link from 'next/link';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-inter',
  weight: 'variable',
  axes: ['opsz'],
});

export const metadata: Metadata = {
  title: 'AI Job Matcher',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={cn(
          inter.variable,
          'bg-white font-sans text-neutral-950 antialiased',
        )}
        style={{ textRendering: 'optimizeLegibility' }}
      >
        <header className="flex h-16 items-center border-b border-neutral-200 px-4">
          <div className="flex items-baseline gap-10">
            <h1 className="text-xl font-semibold">
              <Link href="/">AI Job Matcher</Link>
            </h1>
            <nav className="flex items-center gap-8">
              <Link className="text-sm" href="/students">
                Студенты
              </Link>
              <Link className="text-sm" href="/jobs">
                Вакансии
              </Link>
            </nav>
          </div>
        </header>
        <main className="flex flex-col items-center px-4 py-8">{children}</main>
      </body>
    </html>
  );
}
